import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1784653542466 implements MigrationInterface {
    name = 'InitialSchema1784653542466'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "sessions" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "tokenHash" character(64) NOT NULL, "ipAddress" character varying(255) NOT NULL, "userAgent" text NOT NULL, "deviceSummary" character varying(255) NOT NULL, "deviceId" character varying(128), "loginMethod" character varying(50) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastActiveAt" TIMESTAMP WITH TIME ZONE NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revokedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" SERIAL NOT NULL, "userId" integer, "userName" character varying(255), "userEmail" character varying(255), "action" character varying(50) NOT NULL, "entity" character varying(50) NOT NULL, "entityId" character varying(100), "entityLabel" character varying(255), "summary" character varying(500), "ipAddress" character varying(255), "deviceSummary" character varying(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "passwordHash" character varying(255), "googleSub" character varying(255), "status" character varying NOT NULL DEFAULT 'active', "roles" jsonb NOT NULL DEFAULT '[]', "requestedRoles" jsonb NOT NULL DEFAULT '[]', "registrationNote" character varying(500), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_980a19e1db3caa55d366a4e2165" UNIQUE ("googleSub"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tahun_ajaran" ("id" SERIAL NOT NULL, "nama" character varying(9) NOT NULL, "semester" integer NOT NULL, "aktif" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_64c4cf8bfa2c7ebd0cb3e2c6b78" UNIQUE ("nama", "semester"), CONSTRAINT "PK_bcd644d7ae463f6499014d19c35" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "guru" ("id" SERIAL NOT NULL, "nama" character varying(255) NOT NULL, "nip" character varying(30), "jenisKelamin" character varying(1) NOT NULL, "telepon" character varying(30), "fotoUrl" character varying(500) NOT NULL DEFAULT '', "status" character varying(20) NOT NULL DEFAULT 'aktif', "userId" integer, "faceEmbeddings" jsonb, "faceUpdatedAt" TIMESTAMP WITH TIME ZONE, "faceStatus" character varying(25) NOT NULL DEFAULT 'BELUM', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_77c0427c3e0438a73d067610619" UNIQUE ("nip"), CONSTRAINT "UQ_ea4aeffc90a824f19811ee289e1" UNIQUE ("userId"), CONSTRAINT "PK_180478aa04f87b3005e3a1ed489" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "kelas" ("id" SERIAL NOT NULL, "nama" character varying(50) NOT NULL, "tingkat" integer NOT NULL, "fase" character varying(1) NOT NULL DEFAULT 'D', "waliGuruId" integer, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_88815639c6806e754620b9cad17" UNIQUE ("nama"), CONSTRAINT "UQ_177f654b862d7c84586a8f32ead" UNIQUE ("waliGuruId"), CONSTRAINT "PK_55bb4fb74bbbd202d55118b0417" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "siswa" ("id" SERIAL NOT NULL, "nama" character varying(255) NOT NULL, "nis" character varying(30) NOT NULL, "nisn" character varying(30), "jenisKelamin" character varying(1) NOT NULL, "tempatLahir" character varying(100), "tanggalLahir" date, "agama" character varying(50), "statusDalamKeluarga" character varying(100), "anakKe" integer, "alamat" character varying(500), "telepon" character varying(30), "sekolahAsal" character varying(200), "diterimaDiKelas" character varying(50), "diterimaTanggal" date, "namaAyah" character varying(200), "pekerjaanAyah" character varying(100), "namaIbu" character varying(200), "pekerjaanIbu" character varying(100), "namaWali" character varying(200), "alamatWali" character varying(500), "teleponWali" character varying(30), "pekerjaanWali" character varying(100), "fotoUrl" character varying(500) NOT NULL DEFAULT '', "kelasId" integer, "status" character varying(20) NOT NULL DEFAULT 'aktif', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d56508bb3c5b033aae68100134f" UNIQUE ("nis"), CONSTRAINT "UQ_458f5dfcf50249b95e8f75ef544" UNIQUE ("nisn"), CONSTRAINT "PK_8ce1ff71b8d1e5fe6596c8b2bb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mapel" ("id" SERIAL NOT NULL, "nama" character varying(100) NOT NULL, "kode" character varying(20) NOT NULL, "kelompok" character varying(50), "urutan" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_228fd7adaf7fef7c7eb06c3d8ab" UNIQUE ("kode"), CONSTRAINT "PK_86949c794f4f6eed671f3fa635e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rapor_mapel_override" ("id" SERIAL NOT NULL, "raporId" integer NOT NULL, "mapelId" integer NOT NULL, "nilaiKatrol" integer, "deskripsiOverride" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_rapor_mapel_override" UNIQUE ("raporId", "mapelId"), CONSTRAINT "PK_6d33bdcbd2cad4643b8f11633cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rapor" ("id" SERIAL NOT NULL, "siswaId" integer NOT NULL, "tahunAjaranId" integer NOT NULL, "status" character varying(10) NOT NULL DEFAULT 'DRAFT', "catatanWali" text, "finalisasiOleh" integer, "finalisasiPada" TIMESTAMP WITH TIME ZONE, "snapshot" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_rapor_siswa_ta" UNIQUE ("siswaId", "tahunAjaranId"), CONSTRAINT "PK_27547a5691ab9f587dfd0aec65f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "presensi_harian_guru" ("id" SERIAL NOT NULL, "guruId" integer NOT NULL, "tanggal" date NOT NULL, "checkInAt" TIMESTAMP WITH TIME ZONE, "checkOutAt" TIMESTAMP WITH TIME ZONE, "status" character varying(20) NOT NULL, "source" character varying(20) NOT NULL, "distanceMeter" double precision, "similarity" double precision, "alasan" text, "perluVerifikasi" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_70bbb5383d45cd7349707fe5ee6" UNIQUE ("guruId", "tanggal"), CONSTRAINT "PK_31596656b4823d91385fa16fe1f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "penugasan" ("id" SERIAL NOT NULL, "mapelId" integer NOT NULL, "kelasId" integer NOT NULL, "tahunAjaranId" integer NOT NULL, "guruId" integer NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e3a67aea33213c870aa618e3f83" UNIQUE ("mapelId", "kelasId", "tahunAjaranId"), CONSTRAINT "PK_ae2d98e8cebc54ac01d39730ad7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "jadwal_kbm" ("id" SERIAL NOT NULL, "penugasanId" integer NOT NULL, "hari" integer NOT NULL, "jamMulai" TIME NOT NULL, "jamSelesai" TIME NOT NULL, "sesiKe" integer, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_471c9120f7e405ff3f22a6891dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "presensi_sesi" ("id" SERIAL NOT NULL, "jadwalKbmId" integer NOT NULL, "tanggal" date NOT NULL, "guruPelaksanaId" integer NOT NULL, "guruPenggantiId" integer, "disimpanPada" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8ab077930172aead8a7f9e3191c" UNIQUE ("jadwalKbmId", "tanggal"), CONSTRAINT "PK_d7103d48d241d00e96aa7d0a099" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "presensi_siswa" ("id" SERIAL NOT NULL, "presensiSesiId" integer NOT NULL, "siswaId" integer NOT NULL, "status" character varying(1) NOT NULL DEFAULT 'H', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_233af2482548136c419f677fe8a" UNIQUE ("presensiSesiId", "siswaId"), CONSTRAINT "PK_770a837ae585924e5e192487dc2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tujuan_pembelajaran" ("id" SERIAL NOT NULL, "mapelId" integer NOT NULL, "deskripsi" text NOT NULL, "urutan" integer NOT NULL DEFAULT '1', "aktif" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e9766cab105dee8c6cc144c7235" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "penilaian_tp" ("penilaianId" integer NOT NULL, "tpId" integer NOT NULL, CONSTRAINT "PK_4af61b04ab885f9dd747119cfad" PRIMARY KEY ("penilaianId", "tpId"))`);
        await queryRunner.query(`CREATE TABLE "nilai" ("id" SERIAL NOT NULL, "penilaianId" integer NOT NULL, "siswaId" integer NOT NULL, "nilai" integer NOT NULL, "catatan" character varying(500), "diubahOleh" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_nilai_penilaian_siswa" UNIQUE ("penilaianId", "siswaId"), CONSTRAINT "PK_2e246b2c6af3007586ea96514ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "penilaian" ("id" SERIAL NOT NULL, "penugasanId" integer NOT NULL, "nama" character varying(200) NOT NULL, "jenis" character varying(10) NOT NULL, "subjenis" character varying(30), "bobot" integer NOT NULL, "tanggal" date NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c46e6f5cf240aa86d513003143e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pengaturan" ("key" character varying(100) NOT NULL, "value" jsonb NOT NULL, "updatedByName" character varying(100), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e6d0285166952b762a9da86cafd" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "kalender_libur" ("id" SERIAL NOT NULL, "tanggal" date NOT NULL, "keterangan" character varying(255) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_25077e7abf93708fcb503c8acf3" UNIQUE ("tanggal"), CONSTRAINT "PK_d8a8545e3e379a1caeff5cbdc89" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "kokurikuler_asesmen" ("id" SERIAL NOT NULL, "targetId" integer NOT NULL, "siswaId" integer NOT NULL, "penilaiGuruId" integer NOT NULL, "nilai" character varying(20) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_kokurikuler_asesmen" UNIQUE ("targetId", "siswaId", "penilaiGuruId"), CONSTRAINT "PK_675e103d954e2139e07139a406d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "kokurikuler_target" ("id" SERIAL NOT NULL, "kegiatanId" integer NOT NULL, "namaDimensi" character varying(100) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_kokurikuler_target_dimensi" UNIQUE ("kegiatanId", "namaDimensi"), CONSTRAINT "PK_9be5716695c8a6fca3e343c006b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "kokurikuler_kegiatan" ("id" SERIAL NOT NULL, "tahunAjaranId" integer NOT NULL, "semester" integer NOT NULL, "tema" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_75b61e31e7d8197ed1c70c1e65d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "kokurikuler_tim" ("kegiatanId" integer NOT NULL, "kelasId" integer NOT NULL, "guruId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7ac7e482c3cd4c659d00d6775c7" PRIMARY KEY ("kegiatanId", "kelasId", "guruId"))`);
        await queryRunner.query(`CREATE TABLE "tindak_lanjut" ("id" SERIAL NOT NULL, "siswaId" integer NOT NULL, "tahunAjaranId" integer NOT NULL, "tahap" character varying(20) NOT NULL, "ambang" integer NOT NULL, "status" character varying(10) NOT NULL DEFAULT 'BARU', "catatanPelaksanaan" text, "dilaksanakanOleh" integer, "dilaksanakanPada" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_tindak_lanjut_siswa_ta_tahap" UNIQUE ("siswaId", "tahunAjaranId", "tahap"), CONSTRAINT "PK_89da9383952a6fcfcac02c0a654" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "katalog_pelanggaran" ("id" SERIAL NOT NULL, "nomor" integer NOT NULL, "bentuk" text NOT NULL, "kategori" character varying(10) NOT NULL, "poin" integer NOT NULL, "aktif" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a67d90d4bf4f87f0c9d4b53f3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pelanggaran" ("id" SERIAL NOT NULL, "siswaId" integer NOT NULL, "katalogId" integer, "kategori" character varying(10) NOT NULL, "poin" integer NOT NULL, "tanggal" character varying(10) NOT NULL, "catatan" text, "buktiUrl" character varying(500), "sumber" character varying(20) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'MENUNGGU', "pelaporId" integer, "verifikatorId" integer, "verifikasiPada" TIMESTAMP WITH TIME ZONE, "alasanKeputusan" text, "tahunAjaranId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_pelanggaran_otomatis_t" UNIQUE ("siswaId", "tanggal", "katalogId", "sumber"), CONSTRAINT "PK_b3e063c7ce30cea585a5f1c5654" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1a5c45ef9969b0ccc7bb322b72" ON "pelanggaran" ("siswaId", "tahunAjaranId", "status") `);
        await queryRunner.query(`CREATE TABLE "izin_guru" ("id" SERIAL NOT NULL, "guruId" integer NOT NULL, "jenis" character varying(10) NOT NULL, "mulaiTanggal" date NOT NULL, "selesaiTanggal" date NOT NULL, "keterangan" text NOT NULL, "lampiranUrl" character varying(500), "status" character varying(15) NOT NULL DEFAULT 'MENUNGGU', "disetujuiOleh" integer, "disetujuiPada" TIMESTAMP WITH TIME ZONE, "alasanKeputusan" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_116dbc02e8e2cf38a30b28b44fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ab54232aae4bafa55e3af37551" ON "izin_guru" ("guruId", "status") `);
        await queryRunner.query(`CREATE TABLE "ekskul_tujuan" ("id" SERIAL NOT NULL, "ekskulId" integer NOT NULL, "semester" integer NOT NULL, "deskripsi" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_925ff05f46e838a0f08d530577e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ekskul_nilai" ("id" SERIAL NOT NULL, "pesertaId" integer NOT NULL, "tujuanId" integer NOT NULL, "nilai" character varying(20) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ekskul_nilai" UNIQUE ("pesertaId", "tujuanId"), CONSTRAINT "PK_8f4a38dcf88f1d57633b2f5dce6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ekskul_kehadiran" ("id" SERIAL NOT NULL, "pesertaId" integer NOT NULL, "semester" integer NOT NULL, "jumlahHadir" integer NOT NULL DEFAULT '0', "totalPertemuan" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ekskul_kehadiran" UNIQUE ("pesertaId", "semester"), CONSTRAINT "PK_3c388202d7e4a1e22fe5a336351" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ekskul_peserta" ("id" SERIAL NOT NULL, "ekskulId" integer NOT NULL, "siswaId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ekskul_peserta" UNIQUE ("ekskulId", "siswaId"), CONSTRAINT "PK_3559831955f00c2ac8faa12d2b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ekskul" ("id" SERIAL NOT NULL, "nama" character varying(255) NOT NULL, "pembinaGuruId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d2bacc5bd2ab025d2d945ac2bc3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_597e6df96098895bf19d4b5ea45" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guru" ADD CONSTRAINT "FK_ea4aeffc90a824f19811ee289e1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kelas" ADD CONSTRAINT "FK_177f654b862d7c84586a8f32ead" FOREIGN KEY ("waliGuruId") REFERENCES "guru"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "siswa" ADD CONSTRAINT "FK_b93fa8b4609e8f9a311dba44590" FOREIGN KEY ("kelasId") REFERENCES "kelas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rapor_mapel_override" ADD CONSTRAINT "FK_5cbfd61821cf58aa6cfe4b6fd49" FOREIGN KEY ("raporId") REFERENCES "rapor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rapor_mapel_override" ADD CONSTRAINT "FK_c641568d8a142b6e95db018a9f6" FOREIGN KEY ("mapelId") REFERENCES "mapel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rapor" ADD CONSTRAINT "FK_0fcf01bcea02c86d6c81ef7d74a" FOREIGN KEY ("siswaId") REFERENCES "siswa"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rapor" ADD CONSTRAINT "FK_a8b3c8b270e047d019e07cd610a" FOREIGN KEY ("tahunAjaranId") REFERENCES "tahun_ajaran"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rapor" ADD CONSTRAINT "FK_95583372e0f36c8f1e9770e3df6" FOREIGN KEY ("finalisasiOleh") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presensi_harian_guru" ADD CONSTRAINT "FK_f2bcf4bfcf3ab9ab01fb3e42cf3" FOREIGN KEY ("guruId") REFERENCES "guru"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "penugasan" ADD CONSTRAINT "FK_29cc814885a0a500b14d9bbbdeb" FOREIGN KEY ("mapelId") REFERENCES "mapel"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "penugasan" ADD CONSTRAINT "FK_b793de6282f84196b926d1106ff" FOREIGN KEY ("kelasId") REFERENCES "kelas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "penugasan" ADD CONSTRAINT "FK_07529c0e18409bad4367d92778a" FOREIGN KEY ("tahunAjaranId") REFERENCES "tahun_ajaran"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "penugasan" ADD CONSTRAINT "FK_75040027f71fc08a5da870b08cd" FOREIGN KEY ("guruId") REFERENCES "guru"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jadwal_kbm" ADD CONSTRAINT "FK_ca694b1ec9fb934dc3d2432cc31" FOREIGN KEY ("penugasanId") REFERENCES "penugasan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presensi_sesi" ADD CONSTRAINT "FK_b7337dfde8766f76f61db52f161" FOREIGN KEY ("jadwalKbmId") REFERENCES "jadwal_kbm"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presensi_sesi" ADD CONSTRAINT "FK_fa9b5dcc8bcd24b246097a5f680" FOREIGN KEY ("guruPelaksanaId") REFERENCES "guru"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presensi_sesi" ADD CONSTRAINT "FK_6c71d79fc990e7e90012aac4ea1" FOREIGN KEY ("guruPenggantiId") REFERENCES "guru"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presensi_siswa" ADD CONSTRAINT "FK_f8b5ec675f46a625a7cca16b3aa" FOREIGN KEY ("presensiSesiId") REFERENCES "presensi_sesi"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presensi_siswa" ADD CONSTRAINT "FK_bfe7d2ef31fe2d38dc5373e5b51" FOREIGN KEY ("siswaId") REFERENCES "siswa"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tujuan_pembelajaran" ADD CONSTRAINT "FK_5f90ac62e2125cd6c1db3f57a3c" FOREIGN KEY ("mapelId") REFERENCES "mapel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "penilaian_tp" ADD CONSTRAINT "FK_e9e2963614a5a0473537db32b51" FOREIGN KEY ("penilaianId") REFERENCES "penilaian"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "penilaian_tp" ADD CONSTRAINT "FK_9993f237f031619fdd711e5490e" FOREIGN KEY ("tpId") REFERENCES "tujuan_pembelajaran"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nilai" ADD CONSTRAINT "FK_260d10a25a32fddea0b4d1a3aee" FOREIGN KEY ("penilaianId") REFERENCES "penilaian"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nilai" ADD CONSTRAINT "FK_9ea26c76f573b760f87bceb7a0e" FOREIGN KEY ("siswaId") REFERENCES "siswa"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nilai" ADD CONSTRAINT "FK_38ee721c3567cf142f0405df59a" FOREIGN KEY ("diubahOleh") REFERENCES "guru"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "penilaian" ADD CONSTRAINT "FK_af1c20ab079aa73da80eb746832" FOREIGN KEY ("penugasanId") REFERENCES "penugasan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_asesmen" ADD CONSTRAINT "FK_ab3630afcb99bfa4ba0c8dd95c3" FOREIGN KEY ("targetId") REFERENCES "kokurikuler_target"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_asesmen" ADD CONSTRAINT "FK_da611b997adb16484efcac7c2bd" FOREIGN KEY ("siswaId") REFERENCES "siswa"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_asesmen" ADD CONSTRAINT "FK_28cbc706bcf900b65409d2dacad" FOREIGN KEY ("penilaiGuruId") REFERENCES "guru"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_target" ADD CONSTRAINT "FK_44f6ca548222177cce06299ab9c" FOREIGN KEY ("kegiatanId") REFERENCES "kokurikuler_kegiatan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_kegiatan" ADD CONSTRAINT "FK_a0c13e47d5133fbe0a4c0bfb0f1" FOREIGN KEY ("tahunAjaranId") REFERENCES "tahun_ajaran"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_tim" ADD CONSTRAINT "FK_2688199041a1345c33bb39f0361" FOREIGN KEY ("kegiatanId") REFERENCES "kokurikuler_kegiatan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_tim" ADD CONSTRAINT "FK_de212b1ab89a7479169dbc36e22" FOREIGN KEY ("kelasId") REFERENCES "kelas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_tim" ADD CONSTRAINT "FK_4a484820b758dc03969a1a9806e" FOREIGN KEY ("guruId") REFERENCES "guru"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tindak_lanjut" ADD CONSTRAINT "FK_6605797497ea8fe469e5bd1d472" FOREIGN KEY ("siswaId") REFERENCES "siswa"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tindak_lanjut" ADD CONSTRAINT "FK_8b6c160a7d1f1f4597c316b3fbe" FOREIGN KEY ("tahunAjaranId") REFERENCES "tahun_ajaran"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tindak_lanjut" ADD CONSTRAINT "FK_c76c5a79e0dcee3ab9f049dfada" FOREIGN KEY ("dilaksanakanOleh") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pelanggaran" ADD CONSTRAINT "FK_9a5d5f6615776fda878353d419f" FOREIGN KEY ("siswaId") REFERENCES "siswa"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pelanggaran" ADD CONSTRAINT "FK_664bde1abf9a492fcc1102c14c5" FOREIGN KEY ("katalogId") REFERENCES "katalog_pelanggaran"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pelanggaran" ADD CONSTRAINT "FK_82ced49bcc56c242332290fb9c7" FOREIGN KEY ("pelaporId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pelanggaran" ADD CONSTRAINT "FK_788983ce8c8f08f8b2a8e3d511d" FOREIGN KEY ("verifikatorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pelanggaran" ADD CONSTRAINT "FK_1ca567ee615b5b00da900e83d0b" FOREIGN KEY ("tahunAjaranId") REFERENCES "tahun_ajaran"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "izin_guru" ADD CONSTRAINT "FK_7b41f50a24f9239b94b243191bf" FOREIGN KEY ("guruId") REFERENCES "guru"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "izin_guru" ADD CONSTRAINT "FK_4737757e81d2c6f267247bf6347" FOREIGN KEY ("disetujuiOleh") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ekskul_tujuan" ADD CONSTRAINT "FK_61db61f4a77e2897671a74f20c8" FOREIGN KEY ("ekskulId") REFERENCES "ekskul"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ekskul_nilai" ADD CONSTRAINT "FK_ce1467d55770713c8fb70a3d9d3" FOREIGN KEY ("pesertaId") REFERENCES "ekskul_peserta"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ekskul_nilai" ADD CONSTRAINT "FK_746fba8a9261bffd08226701133" FOREIGN KEY ("tujuanId") REFERENCES "ekskul_tujuan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ekskul_kehadiran" ADD CONSTRAINT "FK_72d9fff6dfdc0d8191e6b534b7b" FOREIGN KEY ("pesertaId") REFERENCES "ekskul_peserta"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ekskul_peserta" ADD CONSTRAINT "FK_c05f5486b4f1a4b34abcd169eb1" FOREIGN KEY ("ekskulId") REFERENCES "ekskul"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ekskul_peserta" ADD CONSTRAINT "FK_e3ad7e4252ac51577a68ce70343" FOREIGN KEY ("siswaId") REFERENCES "siswa"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ekskul" ADD CONSTRAINT "FK_3683a00c76a06c6d9fd53885600" FOREIGN KEY ("pembinaGuruId") REFERENCES "guru"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ekskul" DROP CONSTRAINT "FK_3683a00c76a06c6d9fd53885600"`);
        await queryRunner.query(`ALTER TABLE "ekskul_peserta" DROP CONSTRAINT "FK_e3ad7e4252ac51577a68ce70343"`);
        await queryRunner.query(`ALTER TABLE "ekskul_peserta" DROP CONSTRAINT "FK_c05f5486b4f1a4b34abcd169eb1"`);
        await queryRunner.query(`ALTER TABLE "ekskul_kehadiran" DROP CONSTRAINT "FK_72d9fff6dfdc0d8191e6b534b7b"`);
        await queryRunner.query(`ALTER TABLE "ekskul_nilai" DROP CONSTRAINT "FK_746fba8a9261bffd08226701133"`);
        await queryRunner.query(`ALTER TABLE "ekskul_nilai" DROP CONSTRAINT "FK_ce1467d55770713c8fb70a3d9d3"`);
        await queryRunner.query(`ALTER TABLE "ekskul_tujuan" DROP CONSTRAINT "FK_61db61f4a77e2897671a74f20c8"`);
        await queryRunner.query(`ALTER TABLE "izin_guru" DROP CONSTRAINT "FK_4737757e81d2c6f267247bf6347"`);
        await queryRunner.query(`ALTER TABLE "izin_guru" DROP CONSTRAINT "FK_7b41f50a24f9239b94b243191bf"`);
        await queryRunner.query(`ALTER TABLE "pelanggaran" DROP CONSTRAINT "FK_1ca567ee615b5b00da900e83d0b"`);
        await queryRunner.query(`ALTER TABLE "pelanggaran" DROP CONSTRAINT "FK_788983ce8c8f08f8b2a8e3d511d"`);
        await queryRunner.query(`ALTER TABLE "pelanggaran" DROP CONSTRAINT "FK_82ced49bcc56c242332290fb9c7"`);
        await queryRunner.query(`ALTER TABLE "pelanggaran" DROP CONSTRAINT "FK_664bde1abf9a492fcc1102c14c5"`);
        await queryRunner.query(`ALTER TABLE "pelanggaran" DROP CONSTRAINT "FK_9a5d5f6615776fda878353d419f"`);
        await queryRunner.query(`ALTER TABLE "tindak_lanjut" DROP CONSTRAINT "FK_c76c5a79e0dcee3ab9f049dfada"`);
        await queryRunner.query(`ALTER TABLE "tindak_lanjut" DROP CONSTRAINT "FK_8b6c160a7d1f1f4597c316b3fbe"`);
        await queryRunner.query(`ALTER TABLE "tindak_lanjut" DROP CONSTRAINT "FK_6605797497ea8fe469e5bd1d472"`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_tim" DROP CONSTRAINT "FK_4a484820b758dc03969a1a9806e"`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_tim" DROP CONSTRAINT "FK_de212b1ab89a7479169dbc36e22"`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_tim" DROP CONSTRAINT "FK_2688199041a1345c33bb39f0361"`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_kegiatan" DROP CONSTRAINT "FK_a0c13e47d5133fbe0a4c0bfb0f1"`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_target" DROP CONSTRAINT "FK_44f6ca548222177cce06299ab9c"`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_asesmen" DROP CONSTRAINT "FK_28cbc706bcf900b65409d2dacad"`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_asesmen" DROP CONSTRAINT "FK_da611b997adb16484efcac7c2bd"`);
        await queryRunner.query(`ALTER TABLE "kokurikuler_asesmen" DROP CONSTRAINT "FK_ab3630afcb99bfa4ba0c8dd95c3"`);
        await queryRunner.query(`ALTER TABLE "penilaian" DROP CONSTRAINT "FK_af1c20ab079aa73da80eb746832"`);
        await queryRunner.query(`ALTER TABLE "nilai" DROP CONSTRAINT "FK_38ee721c3567cf142f0405df59a"`);
        await queryRunner.query(`ALTER TABLE "nilai" DROP CONSTRAINT "FK_9ea26c76f573b760f87bceb7a0e"`);
        await queryRunner.query(`ALTER TABLE "nilai" DROP CONSTRAINT "FK_260d10a25a32fddea0b4d1a3aee"`);
        await queryRunner.query(`ALTER TABLE "penilaian_tp" DROP CONSTRAINT "FK_9993f237f031619fdd711e5490e"`);
        await queryRunner.query(`ALTER TABLE "penilaian_tp" DROP CONSTRAINT "FK_e9e2963614a5a0473537db32b51"`);
        await queryRunner.query(`ALTER TABLE "tujuan_pembelajaran" DROP CONSTRAINT "FK_5f90ac62e2125cd6c1db3f57a3c"`);
        await queryRunner.query(`ALTER TABLE "presensi_siswa" DROP CONSTRAINT "FK_bfe7d2ef31fe2d38dc5373e5b51"`);
        await queryRunner.query(`ALTER TABLE "presensi_siswa" DROP CONSTRAINT "FK_f8b5ec675f46a625a7cca16b3aa"`);
        await queryRunner.query(`ALTER TABLE "presensi_sesi" DROP CONSTRAINT "FK_6c71d79fc990e7e90012aac4ea1"`);
        await queryRunner.query(`ALTER TABLE "presensi_sesi" DROP CONSTRAINT "FK_fa9b5dcc8bcd24b246097a5f680"`);
        await queryRunner.query(`ALTER TABLE "presensi_sesi" DROP CONSTRAINT "FK_b7337dfde8766f76f61db52f161"`);
        await queryRunner.query(`ALTER TABLE "jadwal_kbm" DROP CONSTRAINT "FK_ca694b1ec9fb934dc3d2432cc31"`);
        await queryRunner.query(`ALTER TABLE "penugasan" DROP CONSTRAINT "FK_75040027f71fc08a5da870b08cd"`);
        await queryRunner.query(`ALTER TABLE "penugasan" DROP CONSTRAINT "FK_07529c0e18409bad4367d92778a"`);
        await queryRunner.query(`ALTER TABLE "penugasan" DROP CONSTRAINT "FK_b793de6282f84196b926d1106ff"`);
        await queryRunner.query(`ALTER TABLE "penugasan" DROP CONSTRAINT "FK_29cc814885a0a500b14d9bbbdeb"`);
        await queryRunner.query(`ALTER TABLE "presensi_harian_guru" DROP CONSTRAINT "FK_f2bcf4bfcf3ab9ab01fb3e42cf3"`);
        await queryRunner.query(`ALTER TABLE "rapor" DROP CONSTRAINT "FK_95583372e0f36c8f1e9770e3df6"`);
        await queryRunner.query(`ALTER TABLE "rapor" DROP CONSTRAINT "FK_a8b3c8b270e047d019e07cd610a"`);
        await queryRunner.query(`ALTER TABLE "rapor" DROP CONSTRAINT "FK_0fcf01bcea02c86d6c81ef7d74a"`);
        await queryRunner.query(`ALTER TABLE "rapor_mapel_override" DROP CONSTRAINT "FK_c641568d8a142b6e95db018a9f6"`);
        await queryRunner.query(`ALTER TABLE "rapor_mapel_override" DROP CONSTRAINT "FK_5cbfd61821cf58aa6cfe4b6fd49"`);
        await queryRunner.query(`ALTER TABLE "siswa" DROP CONSTRAINT "FK_b93fa8b4609e8f9a311dba44590"`);
        await queryRunner.query(`ALTER TABLE "kelas" DROP CONSTRAINT "FK_177f654b862d7c84586a8f32ead"`);
        await queryRunner.query(`ALTER TABLE "guru" DROP CONSTRAINT "FK_ea4aeffc90a824f19811ee289e1"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_597e6df96098895bf19d4b5ea45"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`DROP TABLE "ekskul"`);
        await queryRunner.query(`DROP TABLE "ekskul_peserta"`);
        await queryRunner.query(`DROP TABLE "ekskul_kehadiran"`);
        await queryRunner.query(`DROP TABLE "ekskul_nilai"`);
        await queryRunner.query(`DROP TABLE "ekskul_tujuan"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab54232aae4bafa55e3af37551"`);
        await queryRunner.query(`DROP TABLE "izin_guru"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a5c45ef9969b0ccc7bb322b72"`);
        await queryRunner.query(`DROP TABLE "pelanggaran"`);
        await queryRunner.query(`DROP TABLE "katalog_pelanggaran"`);
        await queryRunner.query(`DROP TABLE "tindak_lanjut"`);
        await queryRunner.query(`DROP TABLE "kokurikuler_tim"`);
        await queryRunner.query(`DROP TABLE "kokurikuler_kegiatan"`);
        await queryRunner.query(`DROP TABLE "kokurikuler_target"`);
        await queryRunner.query(`DROP TABLE "kokurikuler_asesmen"`);
        await queryRunner.query(`DROP TABLE "kalender_libur"`);
        await queryRunner.query(`DROP TABLE "pengaturan"`);
        await queryRunner.query(`DROP TABLE "penilaian"`);
        await queryRunner.query(`DROP TABLE "nilai"`);
        await queryRunner.query(`DROP TABLE "penilaian_tp"`);
        await queryRunner.query(`DROP TABLE "tujuan_pembelajaran"`);
        await queryRunner.query(`DROP TABLE "presensi_siswa"`);
        await queryRunner.query(`DROP TABLE "presensi_sesi"`);
        await queryRunner.query(`DROP TABLE "jadwal_kbm"`);
        await queryRunner.query(`DROP TABLE "penugasan"`);
        await queryRunner.query(`DROP TABLE "presensi_harian_guru"`);
        await queryRunner.query(`DROP TABLE "rapor"`);
        await queryRunner.query(`DROP TABLE "rapor_mapel_override"`);
        await queryRunner.query(`DROP TABLE "mapel"`);
        await queryRunner.query(`DROP TABLE "siswa"`);
        await queryRunner.query(`DROP TABLE "kelas"`);
        await queryRunner.query(`DROP TABLE "guru"`);
        await queryRunner.query(`DROP TABLE "tahun_ajaran"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
    }

}
